-- PATH VARIABLES ARE RELATIVE TO THE FOLDER WHERE THE DATA BASE IS
-- this order is the one they must be created due to foreign keys use

CREATE TABLE IF NOT EXISTS FILES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    PATH TEXT NOT NULL,
    CREATION NOT NULL,
    TITLE TEXT,
    ALBUM TEXT,
    ARTISTS TEXT,
    REQUEST TEXT NOT NULL
);

-- TABLE FOR RESPONSES AFTER CONSULTING "REQUEST" OF  THE "FILES"
-- PATH IS WHERE THE JSON WILL BE STORED
CREATE TABLE IF NOT EXISTS RESPONSES (
    ID INTEGER PRIMARY KEY,
    NAME TEXT,
    PATH TEXT,
    CREATION TEXT NOT NULL,
    FOREIGN KEY (ID) REFERENCES FILES(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS OBJECTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TYPE TEXT NOT NULL,
    SPOTIFY TEXT NOT NULL UNIQUE
);

-- CREATION for DATE: yyyy-MM-dd HH:mm:ss

CREATE TABLE IF NOT EXISTS IMAGES (
    OBJECT INTEGER NOT NULL,
    NUMBER INT NOT NULL,
    PATH TEXT NOT NULL,
    WIDTH INT NOT NULL,
    HEIGHT INT NOT NULL,
    FOREIGN KEY (OBJECT) REFERENCES OBJECTS(ID) ON DELETE CASCADE,
    PRIMARY KEY (OBJECT, NUMBER)
);

CREATE TABLE IF NOT EXISTS GENRES (
    GENRE TEXT PRIMARY KEY
);


--TODO TAKE THIS INTO ACCOUNT LATER
CREATE TABLE IF NOT EXISTS SUBGENRES (
    ROOT TEXT,
    GENRE TEXT,
    PRIMARY KEY (ROOT, GENRE),
    FOREIGN KEY (ROOT) REFERENCES GENRE(GENRE),
    FOREIGN KEY (GENRE) REFERENCES GENRE(GENRE)
)

CREATE TABLE IF NOT EXISTS OBJECT_GENRES (
    OBJECT INTEGER NOT NULL,
    GENRE TEXT NOT NULL,
    PRIMARY KEY (OBJECT, GENRE),
    FOREIGN KEY (OBJECT) REFERENCES OBJECTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (GENRE) REFERENCES GENRES(GENRE) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ARTISTS (
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    FOREIGN KEY (ID) REFERENCES OBJECTS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ALBUMS (
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    TRACKS INT NOT NULL,
    RELEASE TEXT NOT NULL,
    RELEASE_PRECISION TEXT NOT NULL,
    LABEL TEXT,
    FOREIGN KEY (ID) REFERENCES OBJECTS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRACKS (
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    ALBUM INTEGER NOT NULL,
    NUMBER INT NOT NULL,
    PATH TEXT NOT NULL,
    CREATION TEXT NOT NULL,
    FOREIGN KEY (ID) REFERENCES OBJECTS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID) REFERENCES ALBUMS(ID)
);

CREATE TABLE IF NOT EXISTS TRACK_ARTISTS (
    TRACK INTEGER NOT NULL,
    ARTIST INTEGER NOT NULL,
    PRIMARY KEY (TRACK, ARTIST),
    FOREIGN KEY (TRACK) REFERENCES TRACKS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ARTIST) REFERENCES ARTISTS(ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS ALBUM_ARTISTS (
    ALBUM INTEGER NOT NULL,
    ARTIST INTEGER NOT NULL,
    PRIMARY KEY (ALBUM, ARTIST),
    FOREIGN KEY (ALBUM) REFERENCES ALBUMS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ARTIST) REFERENCES ARTISTS(ID) ON DELETE CASCADE
);




