CREATE TABLE FILES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PATH TEXT NOT NULL,
    NAME TEXT NOT NULL,
    TITLE TEXT,
    ALBUM TEXT,
    ARTISTS TEXT,
    LABEL TEXT
);

CREATE TABLE OBJECTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PATH TEXT NOT NULL,
    NAME TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    URI TEXT NOT NULL,
    URL TEXT
);

CREATE TABLE IMAGES (
    OBJECT INTEGER NOT NULL,
    NUMBER INT NOT NULL,
    PATH TEXT NOT NULL,
    WIDTH INT NOT NULL,
    HEIGHT INT NOT NULL,
    FOREIGN KEY (OBJECT) REFERENCES OBJECTS(ID),
    PRIMARY KEY (OBJECT, NUMBER)
);

CREATE TABLE GENRES (
    GENRE TEXT PRIMARY KEY
);

CREATE TABLE OBJECT_GENRES (
    OBJECT INTEGER NOT NULL,
    GENRE TEXT NOT NULL,
    PRIMARY KEY (OBJECT, GENRE),
    FOREIGN KEY (OBJECT) REFERENCES OBJECTS(ID),
    FOREIGN KEY (GENRE) REFERENCES GENRES(GENRE)
);

CREATE TABLE TRACKS (
    ID INTEGER PRIMARY KEY,
    TITLE TEXT NOT NULL,
    ALBUM INTEGER NOT NULL,
    NUMBER INT NOT NULL,
    FOREIGN KEY (ID) REFERENCES OBJECTS(ID)
    FOREIGN KEY (ID) REFERENCES ALBUMS(ID)
);

CREATE TABLE TRACK_ARTISTS (
    TRACK INTEGER NOT NULL,
    ARTIST INTEGER NOT NULL,
    PRIMARY KEY (TRACK, ARTIST),
    FOREIGN KEY (TRACK) REFERENCES TRACKS(ID),
    FOREIGN KEY (ARTIST) REFERENCES ARTISTS(ID)
);

CREATE TABLE ALBUM_ARTISTS (
    ALBUM INTEGER NOT NULL,
    ARTIST INTEGER NOT NULL,
    PRIMARY KEY (ALBUM, ARTIST),
    FOREIGN KEY (ALBUM) REFERENCES ALBUMS(ID),
    FOREIGN KEY (ARTIST) REFERENCES ARTISTS(ID)
);

CREATE TABLE ALBUMS (
    ID INTEGER PRIMARY KEY,
    TYPE TEXT NOT NULL,
    TRACKS INT NOT NULL,
    RELEASE TEXT NOT NULL,
    RELEASE_PRECISION TEXT NOT NULL,
    LABEL TEXT,
    FOREIGN KEY (ID) REFERENCES OBJECTS(ID)
);

CREATE TABLE ARTISTS (
ID INTEGER PRIMARY KEY,
FOREIGN KEY (ID) REFERENCES OBJECTS(ID)
);


